<?php

namespace App\Controllers;

use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;

class Mvc_generator extends BaseGenerator
{
    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger);
    }

    public function module_role()
    {
        $module_name = "role";

        $field_list = [
            'id' => [
                'primary_key' => true,
                'data_type' => 'int',
                'length' => '11',
                'NULL' => false,
                'default_value' => '',
                'comment' => '',
                'label' => 'ID',
            ],
            'is_deleted' => [
                'primary_key' => false,
                'data_type' => 'tinyint',
                'length' => '1',
                'NULL' => false,
                'default_value' => '0',
                'comment' => '',
                'label' => 'Is Deleted',
            ],
            'created_date' => [
                'primary_key' => false,
                'data_type' => 'datetime',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Created Date',
            ],
            'title' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '255',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Title',
                'input_type' => 'text',
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => true,
            ],                         
            'description' => [
                'primary_key' => false,
                'data_type' => 'text',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Description',
                'input_type' => 'textarea',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => false,
            ], 
            'priority' => [
                'primary_key' => false,
                'data_type' => 'int',
                'length' => '8',
                'NULL' => false,
                'default_value' => '0',
                'comment' => '',
                'label' => 'Priority',
                'input_type' => 'number',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => true,
            ], 
            'modified_date' => [
                'primary_key' => false,
                'data_type' => 'datetime',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Modified Date',
            ],  
        ];

        $this->module_generation($module_name, $field_list);
    }

    public function module_enquiry()
    {
        $module_name = "enquiry";

        $field_list = [
            'id' => [
                'primary_key' => true,
                'data_type' => 'int',
                'length' => '11',
                'NULL' => false,
                'default_value' => '',
                'comment' => '',
                'label' => 'ID',
            ],
            'is_deleted' => [
                'primary_key' => false,
                'data_type' => 'tinyint',
                'length' => '1',
                'NULL' => false,
                'default_value' => '0',
                'comment' => '',
                'label' => 'Is Deleted',
            ],
            'created_date' => [
                'primary_key' => false,
                'data_type' => 'datetime',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Created Date',
            ],
            'name' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '255',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Name',
                'input_type' => 'text',
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => true,
            ],                         
            'email' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '255',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Email',
                'input_type' => 'text',
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => true,
            ], 
            'mobile' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '255',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Mobile',
                'input_type' => 'text',
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => true,
            ],
            'message' => [
                'primary_key' => false,
                'data_type' => 'text',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Message',
                'input_type' => 'textarea',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => false,
            ],
            'status' => [
                'primary_key' => false,
                'data_type' => 'tinyint',
                'length' => '1',
                'NULL' => false,
                'default_value' => '0',
                'comment' => '0=Pending,1=Processing,2=Processed',
                'label' => 'Status',
                'input_type' => 'select',
                'option' => [
                    '0' => 'Pending',
                    '1' => 'Processing',
                    '2' => 'Processed',
                ],
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => true,
                'option_yes_no' => false
            ],
            'admin_remark' => [
                'primary_key' => false,
                'data_type' => 'text',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Admin Remark',
                'input_type' => 'textarea',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => false,
            ],
            'modified_date' => [
                'primary_key' => false,
                'data_type' => 'datetime',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Modified Date',
            ],  
        ];

        $this->module_generation($module_name, $field_list);
    }

    public function module_page()
    {
        $module_name = "page";

        $field_list = [
            'id' => [
                'primary_key' => true,
                'data_type' => 'int',
                'length' => '11',
                'NULL' => false,
                'default_value' => '',
                'comment' => '',
                'label' => 'ID',
            ],
            'is_deleted' => [
                'primary_key' => false,
                'data_type' => 'tinyint',
                'length' => '1',
                'NULL' => false,
                'default_value' => '0',
                'comment' => '',
                'label' => 'Is Deleted',
            ],
            'created_date' => [
                'primary_key' => false,
                'data_type' => 'datetime',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Created Date',
            ],
            'title' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '255',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Title',
                'input_type' => 'text',
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => true,
            ],  
            'slug' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '255',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Slug',
                'input_type' => 'text',
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => true,
            ],  
            'meta_title' => [
                'primary_key' => false,
                'data_type' => 'text',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Meta Title',
                'input_type' => 'textarea',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => true,
            ], 
            'meta_description' => [
                'primary_key' => false,
                'data_type' => 'text',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Meta Description',
                'input_type' => 'textarea',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => true,
            ], 
            'meta_keyword' => [
                'primary_key' => false,
                'data_type' => 'text',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Meta Keyword',
                'input_type' => 'textarea',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => true,
            ], 
            'seo_h1' => [
                'primary_key' => false,
                'data_type' => 'text',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'SEO H1',
                'input_type' => 'textarea',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => true,
            ], 
            'seo_p1' => [
                'primary_key' => false,
                'data_type' => 'text',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'SEO P1',
                'input_type' => 'textarea',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => true,
            ], 
            'seo_h2' => [
                'primary_key' => false,
                'data_type' => 'text',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'SEO H2',
                'input_type' => 'textarea',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => true,
            ], 
            'seo_p2' => [
                'primary_key' => false,
                'data_type' => 'text',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'SEO P2',
                'input_type' => 'textarea',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => true,
            ], 
            'ogimg' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '255',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'OGImg',
                'input_type' => 'file',
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => false,
                'width' => '1200',
                'height' => '630',
            ],
            'content' => [
                'primary_key' => false,
                'data_type' => 'text',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Content',
                'input_type' => 'textarea',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => false,
                'ckeditor' => true,
            ],
            'modified_date' => [
                'primary_key' => false,
                'data_type' => 'datetime',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Modified Date',
            ],  
        ];

        $this->module_generation($module_name, $field_list);
    }

    public function module_expenditure_category()
    {
        $module_name = "expenditure_category";

        $field_list = [
            'id' => [
                'primary_key' => true,
                'data_type' => 'int',
                'length' => '11',
                'NULL' => false,
                'default_value' => '',
                'comment' => '',
                'label' => 'ID',
            ],
            'is_deleted' => [
                'primary_key' => false,
                'data_type' => 'tinyint',
                'length' => '1',
                'NULL' => false,
                'default_value' => '0',
                'comment' => '',
                'label' => 'Is Deleted',
            ],
            'created_date' => [
                'primary_key' => false,
                'data_type' => 'datetime',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Created Date',
            ],
            'title' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '255',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Title',
                'input_type' => 'text',
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => true,
            ],  
            'description' => [
                'primary_key' => false,
                'data_type' => 'text',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Description',
                'input_type' => 'textarea',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => false,
            ], 
            'priority' => [
                'primary_key' => false,
                'data_type' => 'int',
                'length' => '8',
                'NULL' => false,
                'default_value' => '0',
                'comment' => '',
                'label' => 'Priority',
                'input_type' => 'number',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => true,
            ], 
            'is_favourite' => [
                'primary_key' => false,
                'data_type' => 'tinyint',
                'length' => '1',
                'NULL' => false,
                'default_value' => '0',
                'comment' => '0=No,1=Yes',
                'label' => 'Is Favourite',
                'input_type' => 'select',
                'option' => [
                    '0' => 'No',
                    '1' => 'Yes',
                ],
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => true,
                'option_yes_no' => true
            ],
            'modified_date' => [
                'primary_key' => false,
                'data_type' => 'datetime',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Modified Date',
            ],  
        ];

        $this->module_generation($module_name, $field_list);
    }

    public function module_expenditure()
    {
        $module_name = "expenditure";

        $field_list = [
            'id' => [
                'primary_key' => true,
                'data_type' => 'int',
                'length' => '11',
                'NULL' => false,
                'default_value' => '',
                'comment' => '',
                'label' => 'ID',
            ],
            'is_deleted' => [
                'primary_key' => false,
                'data_type' => 'tinyint',
                'length' => '1',
                'NULL' => false,
                'default_value' => '0',
                'comment' => '',
                'label' => 'Is Deleted',
            ],
            'created_date' => [
                'primary_key' => false,
                'data_type' => 'datetime',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Created Date',
            ],
            'expenditure_category_id' => [
                'primary_key' => false,
                'data_type' => 'int',
                'length' => '8',
                'NULL' => false,
                'default_value' => '0',
                'comment' => '',
                'label' => 'Expenditure Category',
                'input_type' => 'bind_select',
                'bind_select' => true,
                'bind_module' => 'expenditure_category',
                'bind_label' => 'title',
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => true,
            ],
            'date' => [
                'primary_key' => false,
                'data_type' => 'date',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Date',
                'input_type' => 'date',
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => true,
            ],
            'title' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '255',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Title',
                'input_type' => 'text',
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => true,
            ],  
            'description' => [
                'primary_key' => false,
                'data_type' => 'text',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Description',
                'input_type' => 'textarea',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => false,
            ], 
            'total_amount' => [
                'primary_key' => false,
                'data_type' => 'decimal',
                'length' => '10,2',
                'NULL' => false,
                'default_value' => '0.00',
                'comment' => '',
                'label' => 'Total Amount',
                'input_type' => 'number',
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => true,
            ],
            'location' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '255',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Location',
                'input_type' => 'text',
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => false,
            ],  
            'photo' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '255',
                'NULL' => true,
                'default_value' => '',
                'comment' => '300x300PX',
                'label' => 'Photo',
                'input_type' => 'file',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => false,
                'width' => '300',
                'height' => '300',
            ],
            'modified_date' => [
                'primary_key' => false,
                'data_type' => 'datetime',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Modified Date',
            ],  
        ];

        $this->module_generation($module_name, $field_list);
    }

    public function module_book()
    {
        $module_name = "book";

        $field_list = [
            'id' => [
                'primary_key' => true,
                'data_type' => 'int',
                'length' => '11',
                'NULL' => false,
                'default_value' => '',
                'comment' => '',
                'label' => 'ID',
            ],
            'is_deleted' => [
                'primary_key' => false,
                'data_type' => 'tinyint',
                'length' => '1',
                'NULL' => false,
                'default_value' => '0',
                'comment' => '',
                'label' => 'Is Deleted',
            ],
            'created_date' => [
                'primary_key' => false,
                'data_type' => 'datetime',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Created Date',
            ],                    
            'title' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '255',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Title',
                'input_type' => 'text',
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => true,
            ],  
            'description' => [
                'primary_key' => false,
                'data_type' => 'text',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Description',
                'input_type' => 'textarea',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => false,
            ], 
            'price' => [
                'primary_key' => false,
                'data_type' => 'decimal',
                'length' => '10,2',
                'NULL' => false,
                'default_value' => '0.00',
                'comment' => '',
                'label' => 'Price',
                'input_type' => 'number',
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => true,
            ],  
            'total_page' => [
                'primary_key' => false,
                'data_type' => 'int',
                'length' => '11',
                'NULL' => false,
                'default_value' => '0',
                'comment' => '',
                'label' => 'Total Page',
                'input_type' => 'number',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => true,
            ],           
            'bought_date' => [
                'primary_key' => false,
                'data_type' => 'date',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Bought Date',
                'input_type' => 'date',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => true,
            ],
            'completed_date' => [
                'primary_key' => false,
                'data_type' => 'date',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Completed Date',
                'input_type' => 'date',
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => true,
            ],
            'photo' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '255',
                'NULL' => true,
                'default_value' => '',
                'comment' => '300x300PX',
                'label' => 'Photo',
                'input_type' => 'file',
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => false,
                'width' => '300',
                'height' => '300',
            ],
            'modified_date' => [
                'primary_key' => false,
                'data_type' => 'datetime',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Modified Date',
            ],  
        ];

        $this->module_generation($module_name, $field_list);
    }

    public function module_car_maintenance()
    {
        $module_name = "car_maintenance";

        $field_list = [
            'id' => [
                'primary_key' => true,
                'data_type' => 'int',
                'length' => '11',
                'NULL' => false,
                'default_value' => '',
                'comment' => '',
                'label' => 'ID',
            ],
            'is_deleted' => [
                'primary_key' => false,
                'data_type' => 'tinyint',
                'length' => '1',
                'NULL' => false,
                'default_value' => '0',
                'comment' => '',
                'label' => 'Is Deleted',
            ],
            'created_date' => [
                'primary_key' => false,
                'data_type' => 'datetime',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Created Date',
            ],                    
            'title' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '255',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Title',
                'input_type' => 'text',
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => true,
            ],  
            'description' => [
                'primary_key' => false,
                'data_type' => 'text',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Description',
                'input_type' => 'textarea',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => false,
            ], 
            'date' => [
                'primary_key' => false,
                'data_type' => 'date',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Date',
                'input_type' => 'date',
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => true,
            ],
            'total_amount' => [
                'primary_key' => false,
                'data_type' => 'decimal',
                'length' => '10,2',
                'NULL' => false,
                'default_value' => '0.00',
                'comment' => '',
                'label' => 'Price',
                'input_type' => 'number',
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => true,
            ],  
            'tags' => [
                'primary_key' => false,
                'data_type' => 'text',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Tags',
                'input_type' => 'textarea',
                'show_in_list_page' => false,
                'show_in_action_page' => false,
                'compulsory' => false,
            ], 
            'modified_date' => [
                'primary_key' => false,
                'data_type' => 'datetime',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Modified Date',
            ],  
        ];

        $this->module_generation($module_name, $field_list);
    }

    public function module_jogging()
    {
        $module_name = "jogging";

        $field_list = [
            'id' => [
                'primary_key' => true,
                'data_type' => 'int',
                'length' => '11',
                'NULL' => false,
                'default_value' => '',
                'comment' => '',
                'label' => 'ID',
            ],
            'is_deleted' => [
                'primary_key' => false,
                'data_type' => 'tinyint',
                'length' => '1',
                'NULL' => false,
                'default_value' => '0',
                'comment' => '',
                'label' => 'Is Deleted',
            ],
            'created_date' => [
                'primary_key' => false,
                'data_type' => 'datetime',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Created Date',
            ],  
            'date' => [
                'primary_key' => false,
                'data_type' => 'date',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Date',
                'input_type' => 'date',
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => true,
            ],  
            'section' => [
                'primary_key' => false,
                'data_type' => 'tinyint',
                'length' => '2',
                'NULL' => false,
                'default_value' => '0',
                'comment' => '0=Morning,1=Afternoon,2=Evening,3=Night',
                'label' => 'Status',
                'input_type' => 'select',
                'option' => [
                    '0' => 'Morning',
                    '1' => 'Afternoon',
                    '2' => 'Evening',
                    '3' => 'Night',
                ],
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => true,
                'option_yes_no' => false
            ],
            'distance_in_km' => [
                'primary_key' => false,
                'data_type' => 'decimal',
                'length' => '10,2',
                'NULL' => false,
                'default_value' => '0.00',
                'comment' => '',
                'label' => 'Distance in KM',
                'input_type' => 'number',
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => true,
            ],                
            'location' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '255',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Location',
                'input_type' => 'text',
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => false,
            ],  
            'photo' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '255',
                'NULL' => true,
                'default_value' => '',
                'comment' => '300x300PX',
                'label' => 'Photo',
                'input_type' => 'file',
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => false,
                'width' => '500',
                'height' => '500',
            ],
            'modified_date' => [
                'primary_key' => false,
                'data_type' => 'datetime',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Modified Date',
            ],  
        ];

        $this->module_generation($module_name, $field_list);
    }

    public function module_jogging_target()
    {
        $module_name = "jogging_target";

        $field_list = [
            'id' => [
                'primary_key' => true,
                'data_type' => 'int',
                'length' => '11',
                'NULL' => false,
                'default_value' => '',
                'comment' => '',
                'label' => 'ID',
            ],
            'is_deleted' => [
                'primary_key' => false,
                'data_type' => 'tinyint',
                'length' => '1',
                'NULL' => false,
                'default_value' => '0',
                'comment' => '',
                'label' => 'Is Deleted',
            ],
            'created_date' => [
                'primary_key' => false,
                'data_type' => 'datetime',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Created Date',
            ],  
            'year' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '4',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Year',
                'input_type' => 'text',
                'show_in_list_page' => true,
                'show_in_action_page' => true,
                'compulsory' => false,
            ], 
            'month_01' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '2',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Month 01',
                'input_type' => 'text',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => false,
            ], 
            'month_02' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '2',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Month 02',
                'input_type' => 'text',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => false,
            ], 
            'month_03' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '2',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Month 03',
                'input_type' => 'text',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => false,
            ], 
            'month_04' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '2',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Month 04',
                'input_type' => 'text',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => false,
            ], 
            'month_05' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '2',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Month 05',
                'input_type' => 'text',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => false,
            ], 
            'month_06' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '2',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Month 06',
                'input_type' => 'text',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => false,
            ],  
            'month_07' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '2',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Month 07',
                'input_type' => 'text',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => false,
            ],  
            'month_08' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '2',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Month 08',
                'input_type' => 'text',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => false,
            ],  
            'month_09' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '2',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Month 09',
                'input_type' => 'text',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => false,
            ],  
            'month_10' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '2',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Month 10',
                'input_type' => 'text',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => false,
            ],  
            'month_11' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '2',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Month 11',
                'input_type' => 'text',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => false,
            ],  
            'month_12' => [
                'primary_key' => false,
                'data_type' => 'varchar',
                'length' => '2',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Month 12',
                'input_type' => 'text',
                'show_in_list_page' => false,
                'show_in_action_page' => true,
                'compulsory' => false,
            ],  
            'modified_date' => [
                'primary_key' => false,
                'data_type' => 'datetime',
                'length' => '',
                'NULL' => true,
                'default_value' => '',
                'comment' => '',
                'label' => 'Modified Date',
            ],  
        ];

        $this->module_generation($module_name, $field_list);
    }
}
